---
all:
  hosts:
    proxmox01:
    proxmox02:
  children:
    pve_hosts:
      hosts:
        proxmox01:
          enabled: yes
          node: proxmox01
          api_host: 192.168.0.1
          storage: ssd
        proxmox02:
          enabled: yes
          node: proxmox02
          api_host: 192.168.0.2
          storage: virt
